---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./headlamp.yaml
  - ./cilium.yaml
  - ./spegel.yaml
  - ./cloudnative-pg.yaml
  - ./coredns.yaml
  - ./csi-driver-smb.yaml
  - ./descheduler.yaml
  - ./envoy-gateway.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./fairwinds.yaml
  - ./nvidia.yaml
  - ./fluent.yaml
  - ./grafana.yaml
  - ./immich.yaml
  - ./isovalent.yaml
  - ./jetstack.yaml
  - ./node-feature-discovery.yaml
  - ./open-webui.yaml
  - ./opencost.yaml
  - ./openspeedtest.yaml
  - ./pihole.yaml
  - ./piraeus-charts.yaml
  - ./rook-ceph-charts.yaml
  - ./strimzi.yaml
  - ./tailscale.yaml
  - ./twin.yaml
  - ./homer-operator.yaml

  - ./vector.yaml
  - ./actions-runner-controller.yaml
  - ./unpoller.yaml

  - ./zot.yaml
  - ./woodpecker.yaml
  - ./forgejo.yaml
  - ./k8gb.yaml
  - ./kro.yaml
  - ./ocm.yaml
  - ./vmware-tanzu.yaml
  - ./otwld.yaml
  - ./victoriametrics.yaml
