---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: suwayomi-postgres
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  enableSuperuserAccess: true
  superuserSecret:
    name: suwayomi-postgres-superuser-creds
  inheritedMetadata:
    labels:
      app: suwayomi-postgres
  instances: 2
  bootstrap:
    initdb:
      database: suwayomi
      owner: suwayomi
  nodeMaintenanceWindow:
    reusePVC: false
  storage:
    size: 10Gi
  monitoring:
    enablePodMonitor: true
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: suwayomi-postgres-s3-store
        serverName: suwayomi-postgres
  backup:
    retentionPolicy: "30d"
  externalClusters:
    - name: suwayomi-postgres-backup
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: suwayomi-postgres-s3-store
          serverName: suwayomi-postgres
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: suwayomi-postgres-s3-store
  namespace: media
spec:
  configuration:
    destinationPath: s3://suwayomi-postgres/${LOCATION}/
    endpointURL: http://${COMMON_S3_ENDPOINT}
    s3Credentials:
      accessKeyId:
        name: suwayomi-postgres-s3
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: suwayomi-postgres-s3
        key: AWS_SECRET_ACCESS_KEY
    wal:
      maxParallel: 8
  instanceSidecarConfiguration:
    env:
      - name: AWS_DEFAULT_REGION
        value: garage
  retentionPolicy: "30d"
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: suwayomi-postgres-s3
  namespace: media
spec:
  schedule: "0 15 1 * * *"
  immediate: true
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  cluster:
    name: suwayomi-postgres
