apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: teslamate-postgres
  namespace: teslamate
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18
  bootstrap:
    initdb:
      database: teslamate
      owner: teslamate
      dataChecksums: true
      postInitApplicationSQL:
        - ALTER USER teslamate WITH SUPERUSER;
  monitoring:
    enablePodMonitor: true
  storage:
    size: 8Gi
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: teslamate-postgres-s3-store
        serverName: teslamate-postgres
  backup:
    retentionPolicy: "30d"
  externalClusters:
    - name: teslamate-postgres-backup
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: teslamate-postgres-s3-store
          serverName: teslamate-postgres
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: teslamate-postgres-s3-store
  namespace: teslamate
spec:
  configuration:
    destinationPath: s3://teslamate-postgres/${LOCATION}/
    endpointURL: http://${COMMON_S3_ENDPOINT}
    s3Credentials:
      accessKeyId:
        name: teslamate-postgres-s3
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: teslamate-postgres-s3
        key: AWS_SECRET_ACCESS_KEY
    wal:
      maxParallel: 8
  instanceSidecarConfiguration:
    env:
      - name: AWS_DEFAULT_REGION
        value: garage
  retentionPolicy: "30d"
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: teslamate-postgres-s3
  namespace: teslamate
spec:
  schedule: "0 30 1 * * *"
  immediate: true
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  cluster:
    name: teslamate-postgres
