{
 "title": "fleet telemetry dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Iinterval", "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d" },
   { "name": "data_source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(uptime_sec{})", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Go Routines count",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(go_goroutines{}[$interval]))",
     "legendFormat": "number of go routines"
    }
   ]
  },
  {
   "title": "Records Dispatched",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(dispatch_total{}[$interval])) by (record_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Records Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(record_size_bytes_total{}[$interval])) by (record_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Socket Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(socket_err_total{}[$interval])) by (record_type)",
     "legendFormat": "socket errors"
    }
   ]
  },
  {
   "title": "Memory Allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(memory_allocated_bytes{}[$interval]))",
     "legendFormat": "Memory Allocated"
    }
   ]
  },
  {
   "title": "Kafka Records Dispatched",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(kafka_produce_total{}[$interval])) by (record_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Records Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_produce_total_bytes{}[$interval])) by (record_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(kafka_err{}[$interval])) by (record_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pubsub Records Dispatched",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(rate(pubsub_publish_total{}[$interval])) by (record_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pubsub Records Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(pubsub_publish_total_bytes{}[$interval])) by (record_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pubsub Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "sum(rate(pubsub_err{}[$interval])) by (record_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kinesis Records Dispatched",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(kinesis_publish_total{}[$interval])) by (record_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kinesis Records Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(kinesis_publish_total_bytes{}[$interval])) by (record_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kinesis Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(kinesis_err{}[$interval])) by (record_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ZMQ Records Dispatched",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(rate(zmq_publish_total{}[$interval])) by (record_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ZMQ Records Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(zmq_publish_total_bytes{}[$interval])) by (record_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ZMQ Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "targets": [
    {
     "expr": "sum(rate(zmq_err{}[$interval])) by (record_type)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}