---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
resources:
  - ./network-attachment-lan.yaml
  - ./network-attachment-lan-airconnect.yaml
  - ./statefulset.yaml
  - ./service.yaml
  - ./httproute.yaml
  - ./airconnect-deployment.yaml
  - ./google-assistant-secret.sops.yaml
  - ./lights-configmap.yaml
