---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - pvc-media.yaml
  - probes.yaml
  - ./autobrr
  - ./prowlarr
  - ./radarr-4k
  - ./radarr-1080p
  - ./radarr-4kremux
  - ./radarr-anime
  - ./sabnzbd
  - ./bazarr-4k
  - ./bazarr-4kremux
  - ./bazarr-1080p
  - ./bazarr-anime
  - ./sonarr-4k
  - ./sonarr-anime
  - ./sonarr-1080p
  - ./plex
  - ./tautulli
  - ./overseerr
  - ./lidarr
  - ./wizarr
  - ./configarr
  - ./kometa
  - ./qb
  - ./qb-pvt
  - ./feedcord
  - ./flaresolverr
  - ./maintainerr
  - ./tracearr
  - ./bookorbit
  - ./audiobookshelf
  - ./suwayomi
  - ./komga
  - ./shelfmark
  - ./omnibus
  - omnibus/secret.sops.yaml
  - oidc-secrets.sops.yaml
  - komga-scan-secret.sops.yaml
