---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./garage.yaml
  - ./garage-reference-grants.yaml
  - ./garage-stpetersburg-reference-grants.yaml
  - ./garage-nodes-stpetersburg.yaml
