apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./monitoring
  - ./auth
  - ./agent-sandbox-system
  - ./arc-systems
  - ./bhaiya
  - ./cloudflare
  - ./cnpg-system
  - ./dragonfly-operator-system
  - ./firecrawl
  - ./fluent-bit
  - ./forgejo
  - ./garage-operator-system
  - ./garage
  - ./gatus
  - ./gvisor
  - ./hermes
  - ./home
  - ./homer-operator
  - ./hubble-ui
  - ./immich
  - ./k8gb
  - ./kata-containers
  - ./kro-system
  - ./kube-system
  - ./lan
  - ./teslamate
  - ./mimir
  - ./media
  - ./open-cluster-management
  - ./open-cluster-management-agent
  - ./opencost
  - ./searxng
  - ./snapshot-controller
  - ./spegel
  - ./tailscale-examples

  - ./tempvm
  - ./zot
  - ./external-secrets
  - ./tailscale-system
  - ./cert-manager
  - ./cliproxy
  - ./default
  - ./envoy-gateway-system
  - ./flux-system
  - ./node-feature-discovery
  - ./tailscale
  - ./local-path-storage
  - ./csi-addons
  - ./csi-driver-smb
  - ./tuppr
  - ./k8s-gpu-dra-driver
  - ./rook-ceph
  - ./velero
  - ./kopiur
  - ./kopiur-velero-home-restore-proof
  - ./kopiur-velero-home-restore-projection
  - ./kopiur-velero-home-restore-proof-target
  - ./vpa-system
  - ./victoria-logs
  - ./victoria-logs/victoria-logs.yaml
  - ./woodpecker
  - ./firefly
