---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds
  namespace: kube-system
spec:
  template:
    spec:

      volumes:
        - name: host-run-netns
          hostPath:
            path: /var/run/netns/
      initContainers:
        - name: install-multus-binary
          image: ghcr.io/k8snetworkplumbingwg/multus-cni:v4.3.0-thick@sha256:2b9671447f3ea4e7e56730843dbf59445b9307246f393b61386b896d56ae51c9
          command:
            - "cp"
            - "-f"
            - "/usr/src/multus-cni/bin/multus-shim"
            - "/host/opt/cni/bin/multus-shim"
        - command:
            - /install-cni.sh
          image: ghcr.io/siderolabs/install-cni:v1.9.0
          name: install-cni
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              mountPropagation: Bidirectional
              name: cnibin
      containers:
        - name: kube-multus
          resources:
            requests:
              cpu: "200m"
              memory: "200Mi"
            limits:
              cpu: "1000m"
              memory: "3000Mi"
