---
apiVersion: v1
kind: Namespace
metadata:
  name: kopiur-system
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    app.kubernetes.io/name: kopiur
    app.kubernetes.io/part-of: kopiur
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
