---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app garage
  namespace: flux-system
spec:
  targetNamespace: garage
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/base/garage/garage
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes-manifests
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  patches:
    - target:
        group: grafana.integreatly.org
        version: v1beta1
        kind: GrafanaDashboard
      patch: |-
        apiVersion: grafana.integreatly.org/v1beta1
        kind: GrafanaDashboard
        metadata:
          name: remove-without-grafana
        $$patch: delete
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app garage-bucket
  namespace: flux-system
spec:
  targetNamespace: garage
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: garage
    - name: garage-reference-grants
  path: ./kubernetes/apps/base/garage/garage-bucket
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes-manifests
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app garage-keys
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/base/garage/garage-keys
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes-manifests
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: garage-bucket
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: garage-webui
  namespace: flux-system
spec:
  dependsOn:
    - name: garage
  targetNamespace: garage
  commonMetadata:
    labels:
      app.kubernetes.io/name: garage-webui
  path: ./kubernetes/apps/base/garage/garage-webui
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes-manifests
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app garage-config
  namespace: flux-system
spec:
  targetNamespace: garage
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/base/garage/garage-config-robbinsdale/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes-manifests
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app garage-nodes
  namespace: flux-system
spec:
  dependsOn:
    - name: garage
  targetNamespace: garage
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/base/garage/garage-nodes-robbinsdale/nodes
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes-manifests
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: garage-velero-bucket
  namespace: flux-system
spec:
  dependsOn:
    - name: garage-bucket
  commonMetadata:
    labels:
      app.kubernetes.io/name: garage-velero-bucket
  path: ./kubernetes/apps/base/garage/garage-velero-bucket
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes-manifests
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
