---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: garage
resources:
  - ../garage-bucket
  - bucket.yaml
  - firefly-postgres.yaml
  - forgejo-postgres.yaml
  - woodpecker-postgres.yaml
  - suwayomi-postgres.yaml
  - teslamate-postgres.yaml
