---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
  name: teslamate-postgres
  namespace: garage
spec:
  clusterRef:
    name: garage
  globalAlias: teslamate-postgres
  quotas:
    maxSize: 100Gi
    maxObjects: 1000000
  keyPermissions:
    - keyRef:
        name: teslamate-postgres-key
        namespace: teslamate
      read: true
      write: true
      owner: true
