---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
resources:
  - ./kopia-password.sops.yaml
  - ./repository.yaml
  - ./snapshotpolicy.yaml
  - ./snapshotschedule.yaml
  - ./snapshot-live-20260908.yaml
