---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr-anime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr-anime
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: config
        backup.velero.io/backup-volumes-excludes: media
      labels:
        app: radarr-anime
    spec:
      containers:
      - name: radarr-anime
        image: lscr.io/linuxserver/radarr:6.3.0
        ports:
        - name: http
          containerPort: 7878
          protocol: TCP
        env:
        - name: PUID
          value: '0'
        - name: GUID
          value: '0'
        - name: TZ
          value: UTC
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /media-share
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: radarr-anime-config
      - name: media
        persistentVolumeClaim:
          claimName: media-share
---
apiVersion: v1
kind: Service
metadata:
  name: radarr-anime
spec:
  selector:
    app: radarr-anime
  ports:
  - name: http
    port: 7878
    protocol: TCP
    targetPort: 7878
