---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - csi-rbac.yaml
  - rbd-device-observer-config.yaml
  - rbd-device-observer-rbac.yaml
  - rbd-device-observer-daemonset.yaml
