---
# renovate: datasource=github-tags depName=home-operations/kromgo
# yaml-language-server: $schema=https://raw.githubusercontent.com/home-operations/kromgo/0.16.1/config.schema.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: kromgo-config
data:
  config.yaml: |
    cache:
      enabled: true
      maxAge: 300

    defaults:
      badge:
        style: flat-square

    badges:
      - id: talos_version
        title: Talos
        query: label_replace(node_os_info{name="Talos"}, "version_id", "$1", "version_id", "v(.+)")
        valueExpr: labels[?"version_id"].orValue("unknown")

      - id: kubernetes_version
        title: Kubernetes
        query: label_replace(kubernetes_build_info{service="kubernetes"}, "git_version", "$1", "git_version", "v(.+)")
        valueExpr: labels[?"git_version"].orValue("unknown")

      - id: tailscale_operator_version
        title: Tailscale
        query: label_replace(gotk_resource_info{name="tailscale-operator"}, "chart_app_version", "$1", "chart_app_version", "[vV](.*)")
        valueExpr: labels[?"chart_app_version"].orValue("unknown")

      - id: flux_version
        title: Flux
        query: label_replace(flux_instance_info{exported_namespace="flux-system",name="flux"}, "version", "$1", "revision", "v([^@]+)@.*")
        valueExpr: labels[?"version"].orValue("unknown")

      - id: cluster_age_days
        title: Age
        query: round((time() - min(kube_node_created)) / 86400)
        valueExpr: string(int(result)) + "d"
        colorExpr: '"green"'

      - id: cluster_node_count
        title: Nodes
        query: count(kube_node_info)
        valueExpr: string(int(result))
        colorExpr: '"green"'

      - id: cluster_pod_count
        title: Pods
        query: sum(kubelet_running_pods)
        valueExpr: string(int(result))
        colorExpr: '"green"'

      - id: cluster_cpu_usage
        title: CPU
        query: round(100 - (avg(rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100), 0.1)
        valueExpr: string(result) + "%"
        colorExpr: 'colorScale(result, [36.0, 76.0], ["green", "orange", "red"])'

      - id: cluster_memory_usage
        title: Memory
        query: round(sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes) * 100, 0.1)
        valueExpr: string(result) + "%"
        colorExpr: 'colorScale(result, [36.0, 76.0], ["green", "orange", "red"])'

      - id: cluster_uptime_days
        title: Uptime
        query: round((time() - min(node_boot_time_seconds)) / 86400)
        valueExpr: string(int(result)) + "d"
        colorExpr: 'colorScale(result, [181.0, 361.0], ["green", "orange", "red"])'

      - id: cluster_alert_count
        title: Alerts
        query: clamp_min(alertmanager_alerts{state="active"} - 1, 0)
        valueExpr: string(int(result))
        colorExpr: 'colorScale(result, [1.0], ["green", "red"])'
