---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: running-workload-image-probe
rules:
  - apiGroups: [""]
    resources:
      - pods
      - persistentvolumeclaims
      - persistentvolumes
    verbs:
      - list
  - apiGroups: [velero.io]
    resources:
      - schedules
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: running-workload-image-probe
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: running-workload-image-probe
subjects:
  - kind: ServiceAccount
    name: running-workload-image-probe
    namespace: monitoring
