---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
  namespace: monz
spec:
  interval: 30m
  chart:
    spec:
      chart: victoria-logs-single
      version: "0.13.9"
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    server:
      persistentVolume:
        enabled: true
        size: 50Gi
      retentionPeriod: 90d
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
      serviceMonitor:
        enabled: true
