---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-egress
spec:
  interval: 1m
  chartRef:
    kind: OCIRepository
    name: tailscale-egress
  releaseName: tailscale-egress
  values:
    proxyGroup: "common-egress"
    services:
      - name: nagato
        fqdn: nagato.keiretsu.ts.net
        ports:
          - port: 9100
            protocol: TCP
