---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/garage-operator-system/garage-operator-system-install
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: garage-operator
      namespace: garage-operator-system
    patch: |-
      - op: add
        path: /spec/values/image
        value:
          digest: sha256:ab769000dd61e07fbb6c45fa544f03c16b50ff0c64fe23ef7d00cc060ec78389
