---
# allow SecurityPolicies in app namespaces to point extAuth at tinyauth
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: extauth-to-tinyauth
spec:
  from:
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: home
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: bhaiya
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: keiretsu-top
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: velero-system
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: teslamate
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: cliproxy
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: media
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: firefly
  to:
    - group: ""
      kind: Service
      name: tinyauth
