---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: hermes-backup
  namespace: velero-system
  labels:
    keiretsu.top/volume-data-required: "true"
spec:
  schedule: "0 7 * * *"
  template:
    ttl: 168h
    includedNamespaces:
      - hermes
    defaultVolumesToFsBackup: true
    resourcePolicy:
      kind: configmap
      name: fs-backup-resource-policy
