---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./media-config-backup.yaml
  - ./hermes-backup.yaml
  - ./home-backup.yaml
  - ./bhaiya-backup.yaml
  - ./cliproxy-backup.yaml
  - ./forgejo-backup.yaml
  - ./forgejo-backup-bootstrap.yaml
