---
# Talos node control-plane ports.
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: app-nodes-tcp
spec:
  jobName: blackbox
  module: tcp_connect
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - rei.killinit.internal:6443
        - asuka.killinit.internal:6443
        - kaji.killinit.internal:6443
      labels:
        service: nodes
        target: kubelet-port
---
# NAS (SMB)
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: app-nas-tcp
spec:
  jobName: blackbox
  module: tcp_connect
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - nagato.killinit.internal:445
      labels:
        service: nodes
        target: nas
---
# JetKVM
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: app-jetkvm-tcp
spec:
  jobName: blackbox
  module: tcp_connect
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - jetkvm.killinit.internal:80
      labels:
        service: nodes
        target: jetkvm
---
# ICMP reachability for nodes.
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: app-nodes-icmp
spec:
  jobName: blackbox
  module: icmp
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - rei.killinit.internal
        - asuka.killinit.internal
        - kaji.killinit.internal
        - nagato.killinit.internal
      labels:
        service: nodes
        target: ping
