apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./bhaiya-rbac.yaml
  - ./velero-rotation-key-2.yaml
  - ./helmrelease.yaml
  - ./node-agent-config.yaml
  - ./fs-backup-resource-policy.yaml
  - ./limitrange.yaml
  - ./servicemonitor.yaml
  - ./networkpolicy.yaml
  - ./dashboard-configmap.yaml
  - ./grafana-dashboard.yaml
  - ./referencegrant.yaml
