apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./monitoring
  - ./agent-sandbox-system
  - ./arc-systems
  - ./cloudflare
  - ./cnpg-system
  - ./dragonfly-operator-system
  - ./fluent-bit
  - ./garage-operator-system
  - ./garage
  - ./gatus
  - ./gvisor
  - ./home
  - ./homer-operator
  - ./immich
  - ./kro-system
  - ./kube-system
  - ./mimir
  - ./spegel
  - ./speedtest
  - ./external-secrets
  - ./hubble-ui
  - ./open-cluster-management-agent
  - ./snapshot-controller
  - ./media
  - ./strimzi
  - ./cert-manager
  - ./default
  - ./envoy-gateway-system
  - ./flux-system
  - ./k8gb
  - ./node-feature-discovery
  - ./tailscale-examples
  - ./tailscale-system

  - ./tailscale
  - ./local-path-storage
  - ./csi-addons
  - ./csi-driver-smb
  - ./tuppr
  - ./tinyauth-egress
  - ./rook-ceph
  - ./velero
  - ./vpa-system
  - ./victoria-logs
  - ./victoria-logs/victoria-logs.yaml
