---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./canary.yaml
  - ./tracee-config.yaml
  - ./tracee-daemonset.yaml
  - ./tracee-networkpolicy.yaml
  - ./tracee-service.yaml
  - ./tracee-servicemonitor.yaml
  - ./runtimeclass.yaml
  - ./runtimeclass-workspace.yaml
  - ./runtimeclass-tailscale.yaml
