---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../garage-keys
  - bhaiya-postgres-key.yaml
  - firefly-postgres-key.yaml
  - forgejo-postgres-key.yaml
  - woodpecker-postgres-key.yaml
  - suwayomi-postgres-key.yaml
  - teslamate-postgres-key.yaml
