---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: teslamate-postgres-key
  namespace: teslamate
spec:
  clusterRef:
    name: garage
    namespace: garage
  name: "TeslaMate PostgreSQL Backup Key"
  secretTemplate:
    name: teslamate-postgres-s3
    accessKeyIdKey: AWS_ACCESS_KEY_ID
    secretAccessKeyKey: AWS_SECRET_ACCESS_KEY
  bucketPermissions:
    - bucketRef:
        name: teslamate-postgres
        namespace: garage
      read: true
      write: true
      owner: true
