{
 "title": "Plex Streaming Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(play_seconds_total, job)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(up{job=~\"$job\"}, instance)"
   },
   {
    "name": "server",
    "label": "server",
    "query": "label_values(play_seconds_total{job=~\"$job\", instance=~\"$instance\"}, server)"
   }
  ]
 },
 "panels": [
  { "title": "Now", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Stream Count",
   "type": "stat",
   "description": "Total number of streams",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\n  sum by (session) (\n    rate(play_seconds_total{job=~\"$job\", instance=~\"$instance\", server=~\"$server\", stream_type!=\"\"}[45s])\n  ) > 0\n)"
    }
   ]
  },
  {
   "title": "Video Transcodes",
   "type": "stat",
   "description": "Total number of streams that are transcoding video",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\n  sum by (session) (\n    rate(play_seconds_total{job=~\"$job\",instance=~\"$instance\",server=~\"$server\",stream_type=\"transcode\"}[45s])\n  ) > 0\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Audio Transcodes",
   "type": "stat",
   "description": "Total number of streams that are transcoding audio (work in progress)",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\n  (\n    label_replace(\n      label_replace(\n        label_replace(\n          sum by (session) (\n            rate(play_seconds_total{job=~\"$job\",instance=~\"$instance\",server=~\"$server\",stream_type=\"transcode\"}[45s])\n          ) > 0,\n          \"src\",\"4k\",\"stream_file_resolution\",\"4[Kk]\"\n        ),\n        \"src\",\"sd\",\"stream_file_resolution\",\"[Ss][Dd]\"\n      ),\n      \"src\",\"$1\",\"stream_file_resolution\",\".*?([0-9]+).*\"\n    )\n  )\n  and on (session, src)\n  (\n    label_replace(\n      label_replace(\n        label_replace(\n          sum by (session) (\n            rate(play_seconds_total{job=~\"$job\",instance=~\"$instance\",server=~\"$server\",stream_type=\"transcode\"}[45s])\n          ) > 0,\n          \"src\",\"4k\",\"stream_resolution\",\"4[Kk]\"\n        ),\n        \"src\",\"sd\",\"stream_resolution\",\"[Ss][Dd]\"\n      ),\n      \"src\",\"$1\",\"stream_resolution\",\".*?([0-9]+).*\"\n    )\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min_over_time( up{job=\"plex\", instance=~\"$instance\"}[2m] )"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"plex\", instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Availability & Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Uptime (time series)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"plex\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Availability (rolling % up)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * avg_over_time( up{job=\"plex\", instance=~\"$instance\"}[5m] )",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}