{
 "title": "Storage Dashboard",
 "description": "prometheus-community\r\n/\r\nsmartctl_exporter\r\n",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(smartctl_device, instance)"
    }
   },
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(smartctl_device{instance=~\"$instance\"}, device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "SMART General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "smartctl_device_temperature{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "SMART STATUS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_smart_status{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Device Critical Warning",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_critical_warning{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Power on Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_power_on_seconds{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Device Media Error",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_media_errors{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Power Cycle",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_power_cycle_count{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "NVME Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Device Data Written (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(smartctl_device_bytes_written{instance=~\"$instance\", device=~\"$device\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Available Spare on NVME",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_available_spare{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}