---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr-1080p
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr-1080p
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: config
        backup.velero.io/backup-volumes-excludes: media
      labels:
        app: bazarr-1080p
    spec:
      containers:
      - name: bazarr-1080p
        image: lscr.io/linuxserver/bazarr:1.6.0
        ports:
        - name: http
          containerPort: 6767
          protocol: TCP
        env:
        - name: PUID
          value: '0'
        - name: GUID
          value: '0'
        - name: TZ
          value: UTC
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /media-share
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: bazarr-1080p-config
      - name: media
        persistentVolumeClaim:
          claimName: media-share
---
apiVersion: v1
kind: Service
metadata:
  name: bazarr-1080p
spec:
  selector:
    app: bazarr-1080p
  ports:
  - name: http
    port: 6767
    protocol: TCP
    targetPort: 6767
