---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageReferenceGrant
metadata:
  name: garage-bucket-to-teslamate-postgres-key
  namespace: teslamate
spec:
  from:
    - kind: GarageBucket
      namespace: garage
  to:
    - kind: GarageKey
      name: teslamate-postgres-key
