---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./monitoring.yaml
  - ./blackbox-exporter-ottawa.yaml
  - ./blackbox-exporter.yaml
  - ./grafana.yaml
  - ./grafana-mcp.yaml
  - ./kromgo.yaml
  - ./monitoring-nagato.yaml
  - ./mimir-rule-completeness.yaml
  - ./smartctl-exporter.yaml
  - ./unpoller.yaml
