---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mimir-rule-completeness
  namespace: flux-system
spec:
  targetNamespace: monitoring
  commonMetadata:
    labels:
      app.kubernetes.io/name: mimir-rule-completeness
  dependsOn:
    - name: mimir
    - name: monitoring
    - name: config
  path: ./kubernetes/apps/base/monitoring/mimir-rule-completeness
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes-manifests
  interval: 30m
  retryInterval: 1m
  timeout: 5m
