---
apiVersion: tuppr.home-operations.com/v1alpha1
kind: TalosUpgrade
metadata:
  name: talos
spec:
  talos:
    # renovate: datasource=docker depName=ghcr.io/siderolabs/installer
    version: v1.13.7
  policy:
    debug: true
    force: true
    rebootMode: default
    placement: soft
    timeout: 30m
  drain:
    enabled: true
    disableEviction: true
  healthChecks:
    - apiVersion: v1
      kind: Node
      expr: status.conditions.exists(c, c.type == "Ready" && c.status == "True")
      description: All nodes must be Ready
      timeout: 10m
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      name: rook
      namespace: rook-ceph
      expr: status.ceph.health != "HEALTH_ERR" && !(has(status.ceph.details) && "PG_AVAILABILITY" in status.ceph.details)
      description: Ceph must have no inactive PGs before upgrading next node
      timeout: 30m
