name: Tailscale Status Check

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    # env:
    #   RUNNER_DEBUG: 1
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: TbqNGJkY5611CNTRL-kvAScMUim511CNTRL
          audience: api.tailscale.com/TbqNGJkY5611CNTRL-kvAScMUim511CNTRL
          tags: tag:k8s
          # renovate: datasource=github-releases depName=tailscale/tailscale
          version: 1.102.4
          args: --accept-dns

      - name: Status
        run: tailscale status
